from __future__ import annotations

METADATA_COLUMNS = ["index", "DOI", "jpegURL", "jsonURL", "occurrenceID"]

TARGET_FIELDS = [
    "typeStatus",
    "scientificName",
    "canonicalName",
    "phylum",
    "order",
    "family",
    "genus",
    "class",
    "dateIdentified",
    "verbatimEventDate",
    "eventDate",
    "year",
    "month",
    "day",
    "verbatimLocality",
    "locality",
    "continent",
    "countryCode",
    "country",
    "verbatimCoordinates",
    "decimalLatitude",
    "decimalLongitude",
    "habitat",
    "verbatimElevation",
    "elevation",
    "identifiedBy",
    "verbatimRecordedBy",
    "recordedBy",
    "collectionID",
    "institutionCode",
    "fieldNotes",
    "organismRemarks",
]

TAXONOMY_FIELDS = ["canonicalName", "phylum", "class", "order", "family", "genus"]

JSON_FIELD_KEYS = {
    "typeStatus": ["dc:typeStatus", "dwc:typeStatus", "typeStatus"],
    "scientificName": ["dwc:scientificName", "scientificName"],
    "canonicalName": ["dwc:canonicalName", "canonicalName"],
    "phylum": ["dwc:phylum", "phylum"],
    "order": ["dwc:order", "order"],
    "family": ["dwc:family", "family"],
    "genus": ["dwc:genus", "genus"],
    "class": ["dwc:class", "class"],
    "dateIdentified": ["dwc:dateIdentified", "dateIdentified"],
    "verbatimEventDate": ["dwc:verbatimEventDate", "verbatimEventDate"],
    "eventDate": ["dwc:eventDate", "eventDate"],
    "year": ["dwc:year", "year"],
    "month": ["dwc:month", "month"],
    "day": ["dwc:day", "day"],
    "verbatimLocality": ["dwc:verbatimLocality", "verbatimLocality"],
    "locality": ["dwc:locality", "locality"],
    "continent": ["dwc:continent", "continent"],
    "countryCode": ["dwc:countryCode", "countryCode"],
    "country": ["dwc:country", "country"],
    "verbatimCoordinates": ["dwc:verbatimCoordinates", "verbatimCoordinates"],
    "decimalLatitude": ["dwc:decimalLatitude", "decimalLatitude"],
    "decimalLongitude": ["dwc:decimalLongitude", "decimalLongitude"],
    "habitat": ["dwc:habitat", "habitat"],
    "verbatimElevation": ["dwc:verbatimElevation", "verbatimElevation"],
    "elevation": ["dwc:elevation", "elevation"],
    "identifiedBy": ["dwc:identifiedBy", "identifiedBy"],
    "verbatimRecordedBy": ["dwc:verbatimRecordedBy", "verbatimRecordedBy"],
    "recordedBy": ["dwc:recordedBy", "recordedBy"],
    "collectionID": ["dwc:collectionID", "collectionID"],
    "institutionCode": ["dwc:institutionCode", "institutionCode"],
    "fieldNotes": ["dwc:fieldNotes", "fieldNotes"],
    "organismRemarks": ["dwc:organismRemarks", "organismRemarks"],
}

GBIF_FIELD_KEYS = {
    "canonicalName": "canonicalName",
    "phylum": "phylum",
    "class": "class",
    "order": "order",
    "family": "family",
    "genus": "genus",
}
